# Stream Types
STREAM_TYPE_NUMERIC = "numeric"
STREAM_TYPE_OBJECT = "object"

STREAM_TYPES = [STREAM_TYPE_NUMERIC, STREAM_TYPE_OBJECT]

UNIT_TIME_SECONDS = "seconds"
UNIT_TIME_MILLISECONDS = "milliseconds"
UNIT_TIME_MICROSECONDS = "microseconds"
UNIT_TIME_NANOSECONDS = "nanoseconds"

UNIT_TIMES = [UNIT_TIME_SECONDS, UNIT_TIME_MILLISECONDS, UNIT_TIME_MICROSECONDS, UNIT_TIME_NANOSECONDS]

UNIT_TIME_MAP = {
    UNIT_TIME_SECONDS: "s",
    UNIT_TIME_MILLISECONDS: "ms",
    UNIT_TIME_MICROSECONDS: "us",
    UNIT_TIME_NANOSECONDS: "ns"
}
